name: pln_flutter
description: SIMKP PLN Mobile Apps

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  #state management, navigator, etc
  get: ^3.24.0
  #http request
  dio: ^3.0.10
  #check internet state
  connectivity: ^2.0.2
  #single local storage
  shared_preferences: ^0.5.12+4
  #cached image with loading indicator and error widget
  cached_network_image: ^2.5.0
  #improvement of Container widget
  division: ^0.8.8
  #firebase cloud messagging and auth
  firebase_messaging: ^7.0.3
  firebase_auth:
  google_sign_in:
  #local notification for in app fcm
  flutter_local_notifications: ^4.0.0
  #auto size text
  auto_size_text: ^2.1.0
  #size based on design draft
  flutter_screenutil: ^4.0.3+1
  #load svg image
  flutter_svg: ^0.19.3
  flutter_keyboard_visibility: ^4.0.3
  #date time picker
  flutter_datetime_picker: ^1.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/kukelola_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Biryani
      fonts:
        - asset: assets/fonts/Biryani-Heavy.otf
          weight: 900
        - asset: assets/fonts/Biryani-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Biryani-Bold.otf
          weight: 700
        - asset: assets/fonts/Biryani-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Biryani-Regular.otf
          weight: 400
        - asset: assets/fonts/Biryani-Light.otf
          weight: 300
        - asset: assets/fonts/Biryani-UltraLight.otf
          weight: 200
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100